### ISSUE TITLE
Request for future: somewhat less repeated random

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#103]
How could we make a note of the force.wav playing, so that the next time force is triggered, it does not play that exact one again?

**Comment by profezzorn** [comment]
This is now implemented, activated with #define NO_REPEAT_RANDOM

**Comment by NoSloppy** [comment]
Oh that's great, and for ALL sounds too, not just force....of course. Yay,
thanks so much!

**Comment by NoSloppy** [comment]
Sorry to dig this up. I just had repeats of push.wav for force push. There are only 2 push sounds.
 Is the no-repeat-random somewhat defeated if there are only 2 files to choose from?

**Comment by profezzorn** [comment]
I figured it would be boring if it would just flip back and forth all the time if you only have two files, so I made it so that if you have 2 files, there is a 25% chance of a repeat instead of a 50% chance of a repeat.
