### ISSUE TITLE
Possible future OLED enhancements?

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#114]
Support for scrolling text files: one 32 pixel frame at a time, such as playing the Ep4 ASCII movie. 
Maybe with the ability to also do smooth vertical scroll (like the SW opening crawl) ?

**Comment by NoSloppy** [comment]
Adding .obj file support to the interesting future options suggestion.

**Comment by profezzorn** [comment]
Why?
If you want an animated 3d model, it would be easier to render it as a movie.

**Comment by NoSloppy** [comment]
Sounds right. ok.
