### ISSUE TITLE
Future request: OLED screen 180 flip

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#117]
I'm terribly sorry I don't know how to participate in pull requests yet, but I found that this simple edit would allow for OLED displays to flip 180 degrees. Tested and working fine by multiple people along with myself.
Change to following lines in ssd1306.h:

Send(SEGREMAP | 0x1);
Send(COMSCANDEC);
change to:
#ifndef OLED_FLIP_180
Send(SEGREMAP | 0x1);
Send(COMSCANDEC);
#else
Send(SEGREMAP);
Send(COMSCANINC);
#endif
Then add #define OLED_FLIP_180 to your config file and comment/uncomment it as needed.

**Comment by Aleyan82** [comment]
I tested the feature and it makes a very nice addition to the OLED settings!!!

**Comment by Aleyan82** [comment]
I made a pull request for this option in the main repo.

**Comment by NoSloppy** [comment]
Thanks!
