### ISSUE TITLE
ProffieOs on other boards

### ISSUE THREAD

**Issue by ziomauro1229** [profezzorn/ProffieOS#129]
Is it possible to be installed in arduino nano by adding the various components such as the gyroscope and the sd reader? It may be a good idea when Proffieboards are not for sale, as in my case.

**Comment by profezzorn** [comment]
ProffieOS can be ported to other boards, but arduino nano doesn't have enough memory.
It currently works on Teensy 3.x boards and Proffieboards, and there is partial Teensy 4.x support.
Supporting other boards takes work, but it can be done.
