### ISSUE TITLE
Request: TrColorCycle to take functions

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#130]
As per TRA thread, looking for an X version of TrColorCycle so the integer arguments could take a function as well, similar to other transitions.
This would add some cool flexibility for this transition for extension and retraction particularly. Thanks for looking.

**Comment by NoSloppy** [comment]
Particularly with WavLen (since I use the beta version currently) It would be great to be able to plug that into the TrColorCyle's Wipe Time for retaction sync.

**Comment by profezzorn** [comment]
implemented
