### ISSUE TITLE
TrRandom<TrConcat<>,TrConcat<>> OverDriveColor error

### ISSUE THREAD

**Issue by fdarosa2663** [profezzorn/ProffieOS#139]
Per PM, this style returns the below compile error:

TransitionEffectL<
TrRandom<
TrConcat<TrInstant,AlphaL<Pulsing<Rgb<255,0,0>,Black,500>,Bump<Int<0>,Int<6000>>>,TrDelayX<WavLen<EFFECT_PREON>>>,
TrConcat<TrInstant,AlphaL<Pulsing<Rgb<255,0,0>,Black,500>,Bump<Int<0>,Int<6000>>>,TrDelayX<WavLen<EFFECT_PREON>>>
>
,EFFECT_PREON>

------------------------

In file included from C:\Users\fernandod\Documents\fdr\ProffieOS6-3-13-21\ProffieOS\ProffieOS.ino:458:
sketch\transitions/random.h: In instantiation of 'OverDriveColor TrWrapper<TR>::getColor(const OverDriveColor&, const OverDriveColor&, int) [with TR = TrConcat<TrInstant, AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >, TrDelayX<WavLen<EffectType::EFFECT_PREON> > >]':
sketch\transitions/random.h:26:18:   required from here
sketch\transitions/random.h:29:34: error: could not convert '((TrWrapper<TrConcat<TrInstant, AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >, TrDelayX<WavLen<EffectType::EFFECT_PREON> > > >*)this)->TrWrapper<TrConcat<TrInstant, AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >, TrDelayX<WavLen<EffectType::EFFECT_PREON> > > >::tr_.TrConcat<TrInstant, AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >, TrDelayX<WavLen<EffectType::EFFECT_PREON> > >::getColor<OverDriveColor, OverDriveColor>((* & a), (* & b), led)' from 'RGBA' to 'OverDriveColor'
   29 |     return tr_.getColor(a, b, led);
      |                                  ^
      |                                  |
      |                                  RGBA
In file included from C:\Users\fernandod\Documents\fdr\ProffieOS6-3-13-21\ProffieOS\ProffieOS.ino:454:
sketch\transitions/delay.h: In instantiation of 'decltype (MixColors(a, b, 1, 1)) TrDelayX<MILLIS>::getColor(const A&, const B&, int) [with A = RGBA_um_nod; B = OverDriveColor; MILLIS = WavLen<EffectType::EFFECT_PREON>; decltype (MixColors(a, b, 1, 1)) = RGBA]':
c:\users\fernan~1\appdata\local\temp\arduino_build_942515\sketch\transitions\concat.h:109:46:   required from 'decltype (MixColors(((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::a_.getColor(a, ((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::intermediate_.getColor(led), led), ((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::b_.getColor(((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::intermediate_.getColor(led), b, led), 1, 1)) TrConcat<A, INTERMEDIATE, B ...>::getColor(const X&, const Y&, int) [with X = OverDriveColor; Y = OverDriveColor; A = TrInstant; INTERMEDIATE = AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >; B = {TrDelayX<WavLen<EffectType::EFFECT_PREON> >}; decltype (MixColors(((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::a_.getColor(a, ((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::intermediate_.getColor(led), led), ((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::b_.getColor(((TrConcat<A, INTERMEDIATE, B ...>*)this)->TrConcat<A, INTERMEDIATE, B ...>::intermediate_.getColor(led), b, led), 1, 1)) = RGBA]'
sketch\transitions/random.h:29:34:   required from 'OverDriveColor TrWrapper<TR>::getColor(const OverDriveColor&, const OverDriveColor&, int) [with TR = TrConcat<TrInstant, AlphaL<Layers<Rgb<255, 0, 0>, AlphaL<Rgb<0, 0, 0>, PulsingF<Int<500> > > >, Bump<Int<0>, Int<6000> > >, TrDelayX<WavLen<EffectType::EFFECT_PREON> > >]'
sketch\transitions/random.h:26:18:   required from here
sketch\transitions/delay.h:22:25: error: operands to ?: have different types 'const OverDriveColor' and 'const RGBA_um_nod'
   22 |     return this->done() ? b : a;
exit status 1
Error compiling for board Proffieboard.

**Comment by profezzorn** [comment]
Fixed: https://github.com/profezzorn/ProffieOS/commit/d39cef87d84606802cd27e15fbc597a91d56918f
