### ISSUE TITLE
Request: Use a variable in blade config for tracks that are within the SD font folder

### ISSUE THREAD

**Issue by FrankKerschbaumer3** [profezzorn/ProffieOS#147]
With font makers having tracks that are usually contained within the font folder, would it be possible to reference the path of the font folder in the tracks path without having to reference the full path?

Example:

`{ "LS6", "LS6/tracks/jabba_scene.wav"`
to
`{ "LS6", "$PWD/jabba_scene.wav"`

Or is it recommended to have all of the tracks in the root dir of the SD card?

Thank you!

**Comment by profezzorn** [comment]
Why? It's not hard to just enter the full path.

**Comment by FrankKerschbaumer3** [comment]
Not hard, just tedious when dealing with several blade styles. Hence why I just wanted to ask 👍

**Comment by profezzorn** [comment]
There is some perceived value, but I don't think it's worth the extra code.
