### ISSUE TITLE
Future: EFFECT_PSTOFF

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#255]
In working with WavLen, It just dawned on me that EFFECT_PSTOFF is not a thing.
Would that make sense to have? Certainly from a WavLen audio standpoint I would think so, just as much as Preon does.
But also to have blade styles use it proper, as in, currently using EFFECT_RETRATION and showing a lingering animation works, but that means it’s starting coincidentally with the retraction. I don’t know , I guess in my mind it mirrors Preon in almost every sense.

Would it be an off_pending sort of thing?

**Comment by profezzorn** [comment]
This has been implemented.
