### ISSUE TITLE
ssd1306. Message is wrong, offset from preset we're on.

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#291]
next and prev preset is showing the MESSAGE from the last preset we were on.
It's directional, as in for example
Doing next preset,
Preset 3 -> Preset 4 = Preset 3's message shows
Preset 4 -> Preset 5 = Preset 4's message shows.

 When doing prev preset, it's the other lagging direction:
Preset 5 -> Preset 4 = Preset 5's message
Preset 4 -> Preset 3 = Preset 4's message.

**Comment by profezzorn** [comment]
Should be fixed now.
