### ISSUE TITLE
Possible Memory leak

### ISSUE THREAD

**Issue by boikonur** [profezzorn/ProffieOS#3]
In long time usage ( at ComicCon) during the day  after changing through styles and constantly turning it on and off, at some point the saber becomes unresponsive. Its Hard to catch via monitoring as it happens   rarely. But watchdog solution must be able to reset  the proffieBoard if that is to happen.
Configuration:
ProffieBoard v1.5
Blade: 130 Neopixels
Styles: 10 demonstrating FireBlade, ColorCycle and static colors

**Comment by profezzorn** [comment]
I wonder if this isn't really an expression of the "board hangs after 37 minutes" bug?
If it's really a memory leak, it should show up if you use the "malloc" command in the serial monitor. I did a little checking, but I haven't found anything so far.

I'm going to close this bug for now, but if you find that "malloc" shows a memory leak, feel free to re-open it.
