### ISSUE TITLE
 Stripes<0,0, = board crash

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#308]
Using Stripes<> in the blade style with size zero (and/or?) speed zero crashes the board.
Currently, there’s no error thrown in either Style editor or when compiling.

**Comment by profezzorn** [comment]
This should hopefully be fixed now.

**Comment by NoSloppy** [comment]
Negative. While it doesn't allow it to be uploaded and crash then board (that's good!), it does fail in compiling.
Including a Stripes style with a zero for either the speed or size generates the error:
```
/var/folders/s2/14yvr53n76xbvx2ctcxwhrvc0000gn/T/arduino_build_964311/sketch/styles/stripes.h:95:19: error: static assertion failed
   95 |     static_assert(!is_same_type<WIDTH, Int<0>>::value);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by profezzorn** [comment]
I'm confused. How is that not fixed? What do you think it should be doing
Unless I'm mistaken though, only the width is tested, so it shouldn't matter if the speed is zero or not.

**Comment by NoSloppy** [comment]
This is true. Not compiling is the fix actually. The issue was the board crashing.

**Comment by NoSloppy** [comment]
Additional message "Stripes cannot have a zero WIDTH" is helpful when getting a compile error, thanks.
