### ISSUE TITLE
Is there any interest in code linting/style guides/etc.?

### ISSUE THREAD

**Issue by Ricapar** [profezzorn/ProffieOS#374]
Like most others I ended up here by way of the rabbit hole that is custom lightsabers.

My first ProffieOS sabers were ones I purchased through Sabertrio, and I'm working on some customizations for them and I've realized the steep (but amazing) learning curve that comes with something as complex as ProffieOS. As I go through the configuration files that Sabertrio has modified, I've found it easier for me to digest what's going on by reformatting the code first, and then breaking down the logic.

For the most part I've been doing this just for myself, but I wouldn't mind contributing back some of my updates. So far none of them are functional changes in any way - just code cleanup, fixing up indentation, etc. 

Would the maintainers be interested in accepting pull requests that consist of just formatting changes?

My only concern would be that certain files would generate a pretty large diff, which could make pull requests from in-flight changes a little more difficult to merge if the submitter hadn't rebased their branches to include any reformatted files.

If you folks are happy to accept these contributions, I'd be happy to provide them. My main question would then be: What branch should I start off of? Right from master, or is there another better starting point?

**Comment by profezzorn** [comment]
I'd have to see the changes to know if they would be welcome or not.
My recommendation would be to not generate large diffs, those are painful to review and will take a LONG time to get right.
Instead, start with some small changes just to make sure that we agree on how things *should* look. Once we're in agreement, then you can do larger cleanups, like maybe one file at a time or something.
The master branch is where these sort of things should happen. The only other relevant branches are the v5.x and v6.x branches, but those branches only get bugfixes which are generally cherry-picked from the master branch.

While not required, I highly recommend creating an account on [the cruicible](https://crucible.hubbe.net/) and discuss things there, as it's generally better than github issues for discussions.
