### ISSUE TITLE
SubBlade misconfiguration compiles, but "bricks" board

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#381]
It seems the culprit is if the total blade count is not +1 of the last pixel (due to offset), the board becomes unresponsive and needs a forced bootloader upload (or 2) to come back.
Ex:
```
SubBlade(5, 119, WS281XBladePtr<119, bladePin, Color8::GRB, PowerPINS<bladePowerPin4, bladePowerPin5> >()),
SubBlade(0, 4, NULL),
```
Ideally, an "error in blade array" message would be generated at compile to avoid the upload from happening.

**Comment by profezzorn** [comment]
This should be fixed now.

**Comment by profezzorn** [comment]
To be clear: You do not get a compile error. The board says "error in blade array" and does not crash.
