### ISSUE TITLE
Saber swinging when Off

### ISSUE THREAD

**Issue by Nnaut** [profezzorn/ProffieOS#4]
Hi
I've noticed a bug. If you perform the following:
1.swing the saber in a continuous motion (in a circle)
2. Turn the saber off (while swinging/spinning)

The saber still performs the swinging motion even though the saber is turned off, and only if you keep swinging in a circle (In this case).
If you stop swinging the saber, the swing motion stops.
I know this bug has been noted elsewhere, but I'd figure I'd put it here.

Using version 1.286

**Comment by profezzorn** [comment]
This is fixed in 1.291 I think.
Please try it and re-open this bug if it is not.
