### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by boikonur** [profezzorn/ProffieOS#406]
Hey mates,  its been a long time since I played with sabers, but recently  had the luck to fetch the master and had broken compilation on that commit. 
Do you all agree, that we can actually setup a travisCI and some CI on pull request just to check compilation health, and presumably can run some other tests in the future?
I know that it might be overkill and the hobby starts to look like work , but sure can probably help with  overall quality and automation of releases and testing.

**Comment by boikonur** [comment]
The issue was something trivial: commented config file. But it was on master, which I presume is the production branch that is unstable but buildable. And as contribution grows, automatic the PRs with some form of  compilation check will be the good start,
although about the configuration topic, most problems will come from the teensy platform, as it will be quite nightmerish to make travisCI work with it. But just having a CI pipeline for the proffiboards only as it is a platform that is with its own arduino platform repo, it might be easier to make.

**Comment by profezzorn** [comment]
If you're referring to CONFIG_FILE being undefined, that's intentional to
make users select a config file.
