### ISSUE TITLE
Proffie OLED displaying upside down. 

### ISSUE THREAD

**Issue by Synn6** [profezzorn/ProffieOS#410]
I have a vaders vault Sovereign elite with an oled screen and proffie. It was displaying fine when I got it, but after I made my own config, all the the .bmp for the oled screen are now displaying upside down.  Does anyone know how I can fix this?

**Comment by profezzorn** [comment]
Try:
#define OLED_FLIP_180

More information here:
https://github.com/profezzorn/ProffieOS/wiki/The-CONFIG_TOP-section

**Comment by Synn6** [comment]
> Try: #define OLED_FLIP_180
> 
> More information here: https://github.com/profezzorn/ProffieOS/wiki/The-CONFIG_TOP-section

That did it! Thank you!
