### ISSUE TITLE
"No webusb interface found"

### ISSUE THREAD

**Issue by hrafnblod** [profezzorn/ProffieOS#411]
Hi,
Might just me being stupid, but ive installed chrome (for the webusb thing), done the driver thing (zadig), installed arduino ide and set the correct settings, windows can see the board when i plug it in, arduino ide can see the board (although i get "Native serial port, can't obtain info" when i try to get board info) - according to the instructions here https://github-wiki-see.page/m/profezzorn/ProffieOS/wiki/ProffieBoard-Setup

When i go to the profezzorn site to use the webusb interface, i get
"NO WEBUSB INTERFACE FOUND"

What am i doing wrong?

Its a proffieboard v2.2
windows 10
latest arduino ide

**Comment by profezzorn** [comment]
Did you select an option with WebUSB in Arduino -> Tools -> USB Type before you programmed the board?
