### ISSUE TITLE
Dotpixel Blade Getting Started

### ISSUE THREAD

**Issue by s28400** [profezzorn/ProffieOS#435]
Hello,

I am working on an experimental high-density dotpixel blade and I would like to control it through ProffieOS. I see the fastled_blade module but am a bit confused about the usage. Can you provide me with some details on how to use this module? I am using APA102 leds to start. I am happy to test/debug this module and provide feedback as I go.

Thank you,
Josh

**Comment by profezzorn** [comment]
Try the SPILed page: https://github.com/profezzorn/ProffieOS/wiki/SpiBladePtr
