### ISSUE TITLE
Turning off saber whilelockup is still active with EVENT_HELD_LONG

### ISSUE THREAD

**Issue by DonSaber** [profezzorn/ProffieOS#44]
In order to avoid turning the saber off while sparring, I selected the method EVENT_HELD_LONG to switch it off, replacing the default EVENT_CLICK_SHORT.
With this configuration, when triggering the lockup and holding it long enough, the saber is turning off.
It would be a good idea to disable the possibility to turn the saber off while the lockup is still active.
Currently using build 3.9, but I think it is present in all versions since I saw it also on the SA-22C porting.

**Comment by profezzorn** [comment]
This is something that is up to the prop to implement.
In most configurations we simply turn exit the lockup when the saber is turned off.
