### ISSUE TITLE
Malware making it into Wiki

### ISSUE THREAD

**Issue by Phenomite** [profezzorn/ProffieOS#490]
Please lock down wiki or moderate changes!

**Comment by Phenomite** [comment]
E.g.
yip[.]su malware shorteners 
and full links to malware zip's like zadig

https://github.com/profezzorn/ProffieOS/wiki/_compare/fbd03191da9780c86bd26cef46486f317d6d02b4...0b0ddabfd5263fdb06df67563e61ea02d5d761f5

**Comment by profezzorn** [comment]
Fixed.
Now I just need to figure out how to let people edit it...
