### ISSUE TITLE
make it possible to define power pins for OLED displays

### ISSUE THREAD

**Issue by profezzorn** [profezzorn/ProffieOS#507]
This will make standby time better for OLEDs.

**Comment by NoSloppy** [comment]
Confirmed getting only 7.5 µA on display power once SCREEN_OFF after the new edits applied, although that's on both LED6 and batt direct.
So not sure if the new `#define DISPLAY_POWER_PINS PowerPINS<bladePowerPin6>` is even needed?

**Comment by profezzorn** [comment]
I'm sure it's not needed at this time.
However, it's possible that some other displays draw more power, and it doesn't cost anything to keep the define in the code. I'm not going to put it in the documentation though, that way it won't confuse anybody into thinking that they need it.
