### ISSUE TITLE
No blade array error thrown

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#546]
For whatever reason, a data pin alias in place of an LED pin doesn't cause a problem and compiles fine, as in using bladePin in place of bladePowerPin1 by mistake, like:
`SimpleBladePtr<CH1LED, NoLED, NoLED, NoLED, bladePin, -1, -1, -1>(),`
not
`SimpleBladePtr<CH1LED, NoLED, NoLED, NoLED, bladePowerPin1, -1, -1, -1>(),`

**Comment by profezzorn** [comment]
This is now a compile-time error:
https://github.com/profezzorn/ProffieOS/commit/a4b84d65f931b16553d4a7a364a384c49c829919
