### ISSUE TITLE
Update #define SPEAK_BLADE_ID to use sound_library for the speaking.

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#590]
I thought it would be cool to use sound_library for the speaking, especially if DISABLE_TALKIE is defined.
Initial attempts of adding sound_library giving issues with SoundQueue.
I'm just not doing it right.

**Comment by profezzorn** [comment]
I don't want to tie the base prop to the sound library, so I think the right way to do this would be to delegate the saying of the ID to a virtual function, which can be overriden in props to implement whatever behavior we want.

**Comment by NoSloppy** [comment]
ok. PR #611 for consideration.

**Comment by NoSloppy** [comment]
done.
