### ISSUE TITLE
Tri Cree Adapter Flickers

### ISSUE THREAD

**Issue by BeanFeed** [profezzorn/ProffieOS#623]
Using Proffie v3.9 board with OS v7.13. It is configured with an non-illuminated pcb. Tri-Cree adapter from vire saber flickers and doesn't hold consistent color.

**Comment by ShtokyD** [comment]
Are you talking about the neopixel to Tri-Cree converter? Yes, I noticed that too, but it's a Vire Saber converter issue, not Proffieboard. I would recommend to use a Warsabers/ShtokCustomWorx adapter instead, it doesn't flicker. You can get it from KRsabers or SaberBay.

**Comment by profezzorn** [comment]
If it's an issue with the Vire Saber adapter, then please contact them.
