### ISSUE TITLE
sound library is saying "nine" instead of "zero"

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#649]
I didn't revert to see when this started, and don't see anything glaring.
Sending `batt` in serial monitor speaks "three point nine two volts" and displays 3.92.
Triggering spoken battery level with prop (nothing changed lately in that feature),
```cpp
          sound_library_.SayNumber(battery_monitor.battery(), SAY_DECIMAL);
          sound_library_.SayVolts();
```
speaks "three point zero two volts" and displays 3.92.
I confirmed that mzero.wav and mnum9.wav are correct.

**Comment by profezzorn** [comment]
I think it should be fixed now.

**Comment by NoSloppy** [comment]
Not quite. 3.68 is "three point thirty six eight volts"

**Comment by profezzorn** [comment]
How about now?

**Comment by NoSloppy** [comment]
now it doesn't speak at all

**Comment by NoSloppy** [comment]
now it works.
