### ISSUE TITLE
Incorrect relative path in sound/sound.h?

### ISSUE THREAD

**Issue by bonytony21** [profezzorn/ProffieOS#65]
Someone ran into a compile error on sound/sound.h which said:

sketch\sound/sound.h:88:28: fatal error: common/sd_card.h: No such file or directory

I looked into it, and if ENABLE_AUDIO isn't defined, it will try to load sd_card.h from the wrong relative path.  It should probably be "../common/sd_card.h" I believe.

**Comment by profezzorn** [comment]
I think you're right.
It's been a while since I tried to compile without ENABLE_AUDIO (not sure why anybody would want to do that really...)
I will try it and make sure it's fixed though.

**Comment by profezzorn** [comment]
This particular include path should be fixed now.
