### ISSUE TITLE
new color change mode doesn't like ColorChange<>

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#666]
This is the blade style in the following video:
`ColorChange<TrInstant,Red,Green,Blue>`
Rotating through the colors, I found it will change once or twice, then start to cycle uncontrollably through them.

https://github.com/profezzorn/ProffieOS/assets/53964195/99f5f442-5d52-4699-86f7-240cb2e3f921

**Comment by profezzorn** [comment]
So, I haven't had time to test it, but I took a look at the code and found lots of bugs.
I re-wrote the buggy part, which hopefully means that at least the bugs are different now.... :)
Anyways, if you test it, let me know how it works, otherwise I'll probably work on it more in a few days.

**Comment by profezzorn** [comment]
I did some basic testing, and this seems to work as far as I can tell.
Closing this issue.

**Comment by profezzorn** [comment]
actually closing...

**Comment by NoSloppy** [comment]
Working really well too it seems! 
ColorChange fixed, and smooth is now less sensitive, yeah? Takes more rotation, therefore easier to target a color, similar to "zoom".
Great.

**Comment by profezzorn** [comment]
Yeah, the idea was that with three rotations, zoom might not be needed, making the controls simpler.
