### ISSUE TITLE
Bluetooth option doesn't add a blade on webpage configurator

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#67]
Both /V4 and /V5 webpage's config file generator DOES add a data line connection to the wiring diagram, but no additional blade is added to the config file area.
It is a requirement, no?

**Comment by profezzorn** [comment]
It's only a requirement if you use LED channel to control the power of the bluetooth module, and that notion is newer than the V5 configurator.  Eventually, I hope to have proper control of the SD_POWER pad, so that I can just turn that off when the SD and bluetooth isn't needed anymore.
