### ISSUE TITLE
Question: pins redundancy in v3.9

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [profezzorn/ProffieOS#686]
I noticed that proffieboard v3.9 has a few controller pins duplicated on electrical schematics:

- BUTTON1
- FREE3
- NEOPIXEL_DATA2
- NEOPIXEL_DATA3
- ID-NEOPIXEL_DATA

...which is reflected in code:
`config/proffieboard_v3_config.h`
```cpp

  // Neopixel pins
  bladePin = 0,                   // blade control, either WS2811 or PWM PA7+PA6 <--
  bladeIdentifyPin = 1,           // blade identify input / FoC
  blade2Pin = 2,                  // PA9 + PB4 <--
  blade3Pin = 4,                  // PA10 + PB5 <--
  blade4Pin = 6,                  // PA4
  blade5Pin = 7,                  // Free1 PB3
  blade6Pin = 8,                  // Free2 PB10
  blade7Pin = 9,                  // Free3 PB11 + PC2 <--
  blade8Pin = 16,                 // also uart PC0
  blade9Pin = 17,                 // also uart PC1

```

What was the reason for this?

**Comment by profezzorn** [comment]
Each CPU pin has a limited number of functions, connecting two pins together creates a pad on the board that has more functions. Having more pads might have been even better, but there is only so much space on the board.
