### ISSUE TITLE
Transitions base.h comparison of signed vs unsigned int

### ISSUE THREAD

**Issue by artandtechvof** [profezzorn/ProffieOS#78]
During compiling for Teensy3.2, the Transitions base.h generates a lot of compiler warnings, indicating a signed/unsinged comparision in;

if (t > len_) {

Changing 
- int len_ =0;

to;

- uint32_t len_ = 0;

solves this issue.

**Comment by profezzorn** [comment]
On vacation right now, but I can fix this once I get back. (Or, you could submit a pull request..)

**Comment by artandtechvof** [comment]
Updated merged into master
