### ISSUE TITLE
Using saber_sa22c_buttons volume mode, hard to tell when you enter/exit volume menu

### ISSUE THREAD

**Issue by LawrenceSmith1437** [profezzorn/ProffieOS#80]
Using saber_sa22c_buttons volume mode, hard to tell when you enter/exit volume menu

Hi guys...
First time Lightsaber builder, first time posting.
I switched props to saber_sa22c_buttons.h to enable volume mode.

I noticed, it was really hard to tell when I'd entered/exited volume menu because the beeps sounded kind of like the "hit high volume limit" beeps... they weren't giving me enough feedback.

I'd like to propose a two-tone beep, low-to-high when entering volume mode, and high-to-low when existing. Makes it really easy to tell when I've entered and exited.

    if (!mode_volume_) {
      mode_volume_ = true;
      beeper.Beep(0.1, 2000);
      beeper.Beep(0.1, 2500);
    
      STDOUT.println("Enter Volume Menu");
    } else {
      mode_volume_ = false;
      beeper.Beep(0.1, 2500);
      beeper.Beep(0.1, 2000);
      STDOUT.println("Exit Volume Menu");
    }

Would I be welcome to propose this in a branch/pull request? And if so how would you like me to contribute? Don't want to step on any toes.

**Comment by profezzorn** [comment]
Pull requests are always welcome.
Don't worry about stepping on toes. :)
Most of the discussion surrounding new features happens on TheRebelArmory.com, so if you want to get people's opinion on things, that would be the place to go.
