### ISSUE TITLE
48kHz sample rate wav freezes board.

### ISSUE THREAD

**Issue by NoSloppy** [profezzorn/ProffieOS#85]
OS 4.8
Recreate by trying 48kHz as font.wav for example.
Cycling through presets is fine until that font, then total freeze and
Serial monitor just repeats over and over extremely fast:

Unsupported rate.
Unsupported rate.
Unsupported rate.
Unsupported rate.
Unsupported rate.
Unsupported rate.
Unsupported

**Comment by profezzorn** [comment]
Should be fixed now.
